// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wandile/smtp-provider/ent/configuration"
	"github.com/wandile/smtp-provider/ent/tenant"
)

// ConfigurationCreate is the builder for creating a Configuration entity.
type ConfigurationCreate struct {
	config
	mutation *ConfigurationMutation
	hooks    []Hook
}

// SetHost sets the "host" field.
func (cc *ConfigurationCreate) SetHost(s string) *ConfigurationCreate {
	cc.mutation.SetHost(s)
	return cc
}

// SetPort sets the "port" field.
func (cc *ConfigurationCreate) SetPort(i int32) *ConfigurationCreate {
	cc.mutation.SetPort(i)
	return cc
}

// SetUsername sets the "username" field.
func (cc *ConfigurationCreate) SetUsername(s string) *ConfigurationCreate {
	cc.mutation.SetUsername(s)
	return cc
}

// SetPassword sets the "password" field.
func (cc *ConfigurationCreate) SetPassword(s string) *ConfigurationCreate {
	cc.mutation.SetPassword(s)
	return cc
}

// SetEnable sets the "enable" field.
func (cc *ConfigurationCreate) SetEnable(b bool) *ConfigurationCreate {
	cc.mutation.SetEnable(b)
	return cc
}

// SetID sets the "id" field.
func (cc *ConfigurationCreate) SetID(u uuid.UUID) *ConfigurationCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *ConfigurationCreate) SetNillableID(u *uuid.UUID) *ConfigurationCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (cc *ConfigurationCreate) AddTenantIDs(ids ...uuid.UUID) *ConfigurationCreate {
	cc.mutation.AddTenantIDs(ids...)
	return cc
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (cc *ConfigurationCreate) AddTenant(t ...*Tenant) *ConfigurationCreate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cc.AddTenantIDs(ids...)
}

// Mutation returns the ConfigurationMutation object of the builder.
func (cc *ConfigurationCreate) Mutation() *ConfigurationMutation {
	return cc.mutation
}

// Save creates the Configuration in the database.
func (cc *ConfigurationCreate) Save(ctx context.Context) (*Configuration, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ConfigurationCreate) SaveX(ctx context.Context) *Configuration {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ConfigurationCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ConfigurationCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ConfigurationCreate) defaults() {
	if _, ok := cc.mutation.ID(); !ok {
		v := configuration.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ConfigurationCreate) check() error {
	if _, ok := cc.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Configuration.host"`)}
	}
	if _, ok := cc.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Configuration.port"`)}
	}
	if _, ok := cc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Configuration.username"`)}
	}
	if _, ok := cc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Configuration.password"`)}
	}
	if _, ok := cc.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "Configuration.enable"`)}
	}
	return nil
}

func (cc *ConfigurationCreate) sqlSave(ctx context.Context) (*Configuration, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ConfigurationCreate) createSpec() (*Configuration, *sqlgraph.CreateSpec) {
	var (
		_node = &Configuration{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(configuration.Table, sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeUUID))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.Host(); ok {
		_spec.SetField(configuration.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := cc.mutation.Port(); ok {
		_spec.SetField(configuration.FieldPort, field.TypeInt32, value)
		_node.Port = value
	}
	if value, ok := cc.mutation.Username(); ok {
		_spec.SetField(configuration.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := cc.mutation.Password(); ok {
		_spec.SetField(configuration.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := cc.mutation.Enable(); ok {
		_spec.SetField(configuration.FieldEnable, field.TypeBool, value)
		_node.Enable = value
	}
	if nodes := cc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   configuration.TenantTable,
			Columns: configuration.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConfigurationCreateBulk is the builder for creating many Configuration entities in bulk.
type ConfigurationCreateBulk struct {
	config
	err      error
	builders []*ConfigurationCreate
}

// Save creates the Configuration entities in the database.
func (ccb *ConfigurationCreateBulk) Save(ctx context.Context) ([]*Configuration, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Configuration, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigurationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ConfigurationCreateBulk) SaveX(ctx context.Context) []*Configuration {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ConfigurationCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ConfigurationCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
