// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/wandile/smtp-provider/ent/configuration"
	"github.com/wandile/smtp-provider/ent/schema"
	"github.com/wandile/smtp-provider/ent/tenant"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	configurationFields := schema.Configuration{}.Fields()
	_ = configurationFields
	// configurationDescID is the schema descriptor for id field.
	configurationDescID := configurationFields[0].Descriptor()
	// configuration.DefaultID holds the default value on creation for the id field.
	configuration.DefaultID = configurationDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
}
